version: 0.2

phases:
  install:
    commands:
      - node -v
      - cd my-chime-frontend
      - pwd
      # install dependencies
      - npm install # or any other package manager command
  
  pre_build:
    commands:
      # ecr login
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

  build:
    commands:
      # image build
      - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG} .
      # image push
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Running post-build actions..."
      - printf '[{"name":"hmkim-cube","imageUri":"%s"}]' ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG} > imagedefinitions.json
      - ls -al
  
artifacts:
  files: eks-test/imagedefinitions.json